# Useful functions for Deep Learning from PyTorch library

We will cover the following functions in this notebook:

- `torch.reshape`
- `torch.arange`
- `torch.inverse`
- `torch.det`
- `torch.from_numpy` and `tensor.numpy`

Before we begin, let's install and import PyTorch

In [1]:
# Import torch and other required modules
import torch

## Function 1 - `torch.reshape`

Syntax: `torch.reshape(input, shape)`
* `input` : Tensor
* `shape` : tuple of python

Result: returns a tensor with the same data as `input` but with the new `shape`

In [3]:
# Example 1
t1 = torch.tensor([1, 2, 3, 4])
print(t1)
torch.reshape(t1, (2, 2))

tensor([1, 2, 3, 4])


tensor([[1, 2],
        [3, 4]])

Reshape `t1` tensor, which is a 1-D tensor (4-dimensional vector), into a 2-D tensor (2 by 2 matrix).

In [8]:
# Example 2
t2 = torch.arange(8.)
print(t2)
torch.reshape(t2, (2, 2, -1))

tensor([0., 1., 2., 3., 4., 5., 6., 7.])


tensor([[[0., 1.],
         [2., 3.]],

        [[4., 5.],
         [6., 7.]]])

When a dimension is `-1`, the value for that dimension is inferred.

In [9]:
# Example 3
t3 = torch.arange(9.)
print(t3)
torch.reshape(t3, (3, 4))

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.])


RuntimeError: shape '[3, 4]' is invalid for input of size 9

The new `shape` must be compatible with the number of elements of original `input`.

Closing comments about when to use this function

Let's save our work using Jovian before continuing.

In [22]:
!pip install jovian --upgrade --quiet

In [23]:
import jovian

In [15]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Function 2 - `torch.arange`

Syntax: `torch.arange(start, end, step)`
* `start`, `end`, `step` : numbers

Result: returns a 1-D tensor with evenly spaced values from the interval `[start, end)`


In [17]:
# Example 1
t1 = torch.arange(1, 9, 2)
print(t1)

tensor([1, 3, 5, 7])


Returns a 1-D tensor with values from `1` with step of `2`.

In [20]:
# Example 2
t2 = torch.arange(5)
print(t2)

tensor([0, 1, 2, 3, 4])


If only one number is provided, it is considered as `end`, with the default `start` value of 0 and `step` value of 1.

In [21]:
# Example 3
t3 = torch.arange(1, -1)

RuntimeError: upper bound and larger bound inconsistent with step sign

`end` must be larger than `start`.

In [16]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Function 3 - `torch.inverse`

Syntax: `torch.inverse(A)`
* `A` : square-matrix-like tensor

Result: returns the inverse of `A` if it exists

In [31]:
# Example 1
t1 = torch.tensor([[1., 2.], [3., 4.]])
print(t1)

t2 = torch.inverse(t1)
print(t2)

tensor([[1., 2.],
        [3., 4.]])
tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])


`t1` is invertible.

In [32]:
# Example 2
t3 = torch.inverse(t2)
print(t3)

tensor([[1.0000, 2.0000],
        [3.0000, 4.0000]])


We inverse `t2` to receive the original tensor of matrix.

In [48]:
# Example 3
t4 = torch.tensor([[1., 2., 3.], [4., 5., 6.], [2., 4., 6.]])
torch.inverse(t4)

RuntimeError: inverse_cpu: U(3,3) is zero, singular U.

`t4` is non-invertible so we get the error. We'll also get errors when the tensor is not a square matrix.

In [17]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Function 4 - `torch.det`

Syntax: `torch.det(A)`
* `A` : square-matrix-like tensor

Result: returns the determinant of `A`

In [54]:
# Example 1
t1 = torch.tensor([[1., 2.], [3., 4.]])
torch.det(t1)

tensor(-2.0000)

The function returns the determinant of the given square matix.

In [59]:
# Example 2
t2 = t1.t()
torch.det(t2)

tensor(-2.)

One of properties of the determinant is the determinant of the transpose of `A` equals the determinant of `A`.

In [60]:
# Example 3
t3 = torch.tensor([[1., 2.], [3., 4., 5.]])
torch.det(t3)

ValueError: expected sequence of length 2 at dim 1 (got 3)

We'll get errors if the tensor is not a square matrix.

In [18]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Function 5 - `torch.from_numpy` and `tensor.numpy`

Syntax: `torch.from_nupy(ndarray)` and `tensor.numpy()`

Result: creates a tensor from a numpy `ndarray` and vice versa.

In [61]:
import numpy as np

In [66]:
# Example 1
a1 = np.array([1, 2, 3, 4, 5])
t1 = torch.from_numpy(a1)
t1

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

We create `t1` tensor from `a1` array.

In [65]:
# Example 2
a2 = t1.numpy()
a2

array([1, 2, 3, 4, 5])

Returns a numpy array from the tensor.

In [67]:
# Example 3
list = [1, 2, 3]
torch.from_numpy(list)

TypeError: expected np.ndarray (got list)

The input must be a numpy array, not a python list.

In [19]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Conclusion

We've covered the following functions in this notebook:
- `torch.reshape`
- `torch.arange`
- `torch.inverse`
- `torch.det`
- `torch.from_numpy` and `tensor.numpy`

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* ...

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
